# 部署静态内容到GitHub Pages的简单工作流程
名字：将静态内容部署到Pages

在:
  # 在针对默认分支的推送时运行

## 示例

```yml
on:
  push:
    branches: [main]
```
  推:
    分支：["main"]

  # 允许您从操作选项卡手动运行此工作流程
  工作流触发:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  目录： 读取
  页: 写
  id令牌：写

# 仅允许一个并发部署，跳过在进行中的运行和最新排队之间的排队运行。
# 但是，请不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发:
  组: "页面"
  取消进行中： false

工作:
  # 单独部署作业，因为我们只是进行部署
  deploy:
    environment:
      name:       名称: github-pages
      url:       url: ${{ steps.deployment.outputs.page_url }}{{ steps.deployment.outputs.page_url }}
    runs-on:     运行于：ubuntu-latest
    steps:
      - name:       - 名称：结账
        uses:         用途：actions/checkout@v4
      - name:       - 名称：设置页面
        uses:         使用：actions/configure-pages@v5
      - name:       - name: 上传工件
        uses:         用途: actions/upload-pages-artifact@v3
        with:
          # 上传整个仓库# Upload entire repository
          path: '.'
      - name:       - name: 部署到GitHub Pages
        id:         id: 部署
        uses:         用途：actions/deploy-pages@v4
